### PR TITLE
Fix jitpick install script

### PR DESCRIPTION
**Pull request by nitinprabhu**

### CODE REVIEW

**Review by linusnorton — APPROVED** [review]

**Comment by banderous** [comment]
Do we also need to update the plugin code to set the right repository for the library now that its not coming from bintray?

**Comment by nitinprabhu** [comment]
> Do we also need to update the plugin code to set the right repository for the library now that its not coming from bintray?

It will get deployed to jitpack https://jitpack.io/#hmcts/ccd-config-generator and in the consumer we will have to include jitpick repo to download this
```
repositories {
    ...
    maven { 
        url "https://jitpack.io" 
    }
}
```

**Comment by banderous** [comment]
@nitinprabhu the gradle plugin sets the bintray repository automatically, can you update it to set the jitpick repo? https://github.com/hmcts/ccd-config-generator/blob/6364d868c2c0b5f09dc6b429169561db5f010110/ccd-gradle-plugin/src/main/java/uk/gov/hmcts/ccd/sdk/CcdSdkPlugin.java#L59

**Comment by nitinprabhu** [comment]
> @nitinprabhu the gradle plugin sets the bintray repository automatically, can you update it to set the jitpick repo?
> 
> https://github.com/hmcts/ccd-config-generator/blob/6364d868c2c0b5f09dc6b429169561db5f010110/ccd-gradle-plugin/src/main/java/uk/gov/hmcts/ccd/sdk/CcdSdkPlugin.java#L59

Done here https://github.com/hmcts/ccd-config-generator/pull/101

**Pull request merged**
